load("//rules:rg_cc.bzl", "rg_cc_singletest")

rg_cc_singletest(
    name = "image",
    deps = ["//raygame/core/drawing"],
)

rg_cc_singletest(
    name = "pixel",
    deps = ["//raygame/core/drawing"],
)
