package(default_visibility = ["//visibility:public"])

constraint_setting(
    name = "log_level",
    default_constraint_value = "debug",
)

constraint_value(
    name = "trace",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "debug",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "info",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "note",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "progress",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "warning",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "error",
    constraint_setting = ":log_level",
)

constraint_value(
    name = "fatal",
    constraint_setting = ":log_level",
)

