load("//rules:rg_cc.bzl", "rg_cc_singletest")

rg_cc_singletest(
    name = "resmk",
    deps = [
        "//raygame/tools/resmk",
        "//raygame/core/io",
    ],
    data = [
        "data/pngtest-base.cpp",
        "data/pngtest-base.h",
        "data/pngtest-full.cpp",
        "data/pngtest-full.h",
        "data/pngtest-none.cpp",
        "data/pngtest-none.h",
        "data/pngtest.png",
    ],
)
