constraint_setting(
    name = "cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "amd64",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "x86_64",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "x86_32",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "arm64",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "risc-v",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "arm",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)
