constraint_value(
    name = "amd64",
    constraint_setting = "//rules/constraints:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "x86_64",
    constraint_setting = "//rules/constraints:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "x86_32",
    constraint_setting = "//rules/constraints:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "arm64",
    constraint_setting = "//rules/constraints:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "risc-v",
    constraint_setting = "//rules/constraints:cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "arm",
    constraint_setting = "//rules/constraints:cpu",
    visibility = ["//visibility:public"],
)
