constraint_setting(
    name = "build",
    visibility = ["//visibility:public"],
)

constraint_setting(
    name = "compiler",
    visibility = ["//visibility:public"],
)

constraint_setting(
    name = "cpu",
    visibility = ["//visibility:public"],
)

constraint_setting(
    name = "os",
    visibility = ["//visibility:public"],
)
