find_package(PkgConfig REQUIRED)

function(add_wayland target_name protos_dir)
    pkg_check_modules(RAYGAME_WAYLAND REQUIRED wayland-client)
    target_link_libraries(${target_name} PUBLIC wayland-client)
    target_link_libraries(${target_name} PUBLIC raygame_wayland)
    target_link_directories(${target_name} PUBLIC ${protos_dir})
    target_include_directories(${target_name} PUBLIC ${RAYGAME_WAYLAND_INCLUDE_DIRS})
    target_include_directories(${target_name} PUBLIC ${protos_dir})
endfunction()
