config_setting(
    name = "enabled",
    flag_values = { "//rules/log:source_location": "true" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "disabled",
    flag_values = { "//rules/log:source_location": "false" },
    visibility = ["//visibility:public"],
)
