config_setting(
    name = "full",
    flag_values = { "//rules/log:source_location": "full" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "base",
    flag_values = { "//rules/log:source_location": "base" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "none",
    flag_values = { "//rules/log:source_location": "none" },
    visibility = ["//visibility:public"],
)
