load("//rules:rg_cc.bzl", "rg_cc_singletest")

rg_cc_singletest(
    name = "condition",
    deps = ["//raygame/core"],
)

rg_cc_singletest(
    name = "debug",
    deps = ["//raygame/core"],
)

rg_cc_singletest(
    name = "logger",
    deps = ["//raygame/core"],
)

rg_cc_singletest(
    name = "matrix",
    deps = ["//raygame/core"],
)

rg_cc_singletest(
    name = "types",
    deps = ["//raygame/core"],
)
