constraint_value(
    name = "gcc",
    constraint_setting = "//rules/constraints:compiler",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "clang",
    constraint_setting = "//rules/constraints:compiler",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "msvc",
    constraint_setting = "//rules/constraints:compiler",
    visibility = ["//visibility:public"],
)
