constraint_setting(
    name = "compiler",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "gcc",
    constraint_setting = ":compiler",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "clang",
    constraint_setting = ":compiler",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "msvc",
    constraint_setting = ":compiler",
    visibility = ["//visibility:public"],
)
