cc_library(
	name = "base",
	hdrs = [
    	"condition.h",
    	"config.h",
    	"debug.h",
    	"exception.h",
    	"logger.h",
    	"types.h",
	],
	srcs = [
    	"condition.cpp",
    	"config.cpp",
    	"debug.cpp",
    	"exception.cpp",
    	"logger.cpp",
    	"types.cpp",
	],
	visibility = [ "//visibility:public" ]
)
