filegroup(
    name = "wayland-protocol",
    srcs = ["wayland.xml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "xdg-shell-protocol",
    srcs = ["xdg-shell.xml"],
    visibility = ["//visibility:public"],
)
