load("//rules:rg_cc.bzl", "rg_cc_binary")

rg_cc_binary(
    name = "image",
    srcs = [
        "cottage.hpp",
        "defs.hpp",
        "icon.cpp",
        "icon.hpp",
        "main.cpp",
    ],
    deps = [
        "//raygame/core:core_extra",
    ],
)
