filegroup(
    name = "doxygen_files",
    srcs = [
    ] + glob([
        "**/*.h",
        "**/*.inl",
        "**/*.dox",
    ]),
    visibility = [ "//visibility:public" ],
)

filegroup(
    name = "doxygen_data_files",
    srcs = [],
    visibility = [ "//visibility:public" ],
)
