constraint_setting(
    name = "os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "linux",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "android",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "bsd",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "cygwin",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "hurd",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "integrity",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "mac",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "qnx",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "win64",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "win32",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)
