cc_library(
	name = "math",
	hdrs = [
    	"arithmetic.h",
    	"arithmetic/safe_add.h",
    	"arithmetic/safe_div.h",
    	"arithmetic/safe_mult.h",
    	"arithmetic/safe_sub.h",
    	"math.h",
    	"mathrule.h",
    	"numeric_cast.h",
    	"random.h",
    	"rect.h",
    	"vector.h",
	],
	srcs = [
    	"arithmetic.cpp",
    	"arithmetic/safe_add.cpp",
    	"arithmetic/safe_div.cpp",
    	"arithmetic/safe_mult.cpp",
    	"arithmetic/safe_sub.cpp",
    	"math.cpp",
    	"mathrule.cpp",
    	"numeric_cast.cpp",
    	"random.cpp",
    	"rect.cpp",
    	"vector.cpp",
	],
	deps = [
		"//core/base",
	],
	visibility = [ "//visibility:public" ]
)

