cc_library(
    name = "libwayland-client",
    deps = ["@usr//:libwayland-client"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "libxkbcommon",
    deps = ["@usr//:libxkbcommon"],
    visibility = ["//visibility:public"],
)
