cc_library(
    name = "windowimpl",
    srcs = glob(["**/*.h"]),
    hdrs = glob(["**/*.cpp"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "doxygen_files",
    srcs = glob([
        "**/*.h",
        "**/*.dox",
    ]),
    visibility = [ "//visibility:public" ],
)

