LLVM_PATH			?= ${EXT_PATH}/llvm-project
LLVM_INSTALL_PATH	?= ${OUT_PATH}
LLVM_BUILD_PATH		?= ${LLVM_PATH}/build

LLVM_DO_TESTS		?= FALSE

LLVM_CMAKE_ARGS		+=	-G "Unix Makefiles"
LLVM_CMAKE_ARGS		+=	-S ${LLVM_PATH}/runtimes
LLVM_CMAKE_ARGS		+=	-B ${LLVM_BUILD_PATH}
LLVM_CMAKE_ARGS		+=	-DCMAKE_CXX_COMPILER=clang++
LLVM_CMAKE_ARGS		+=	-DCMAKE_C_COMPILER=clang
LLVM_CMAKE_ARGS		+=	-DCMAKE_INSTALL_PREFIX="${LLVM_INSTALL_PATH}"
LLVM_CMAKE_ARGS		+=	-DLIBCXX_CXX_ABI=libcxxabi

ifeq (${BUILD_TYPE}, RELEASE)
	LLVM_CMAKE_ARGS	+=	-DCMAKE_BUILD_TYPE=Release
endif
ifeq (${BUILD_TYPE}, DEBUG)
	LLVM_CMAKE_ARGS	+=	-DCMAKE_BUILD_TYPE=Debug
endif

LLVM_CMAKE_ARGS		+=	-DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
