.EXPORT_ALL_VARIABLES:

LLVM_INSTALL_PATH	?= ${OUT_PATH}
LLVM_RUNTIMES		?= "libcxx;libcxxabi;libunwind"

LLVM_CMAKE_ARGS		+=	-G "Unix Makefiles"
LLVM_CMAKE_ARGS		+=	-S runtimes
LLVM_CMAKE_ARGS		+=	-B build
LLVM_CMAKE_ARGS		+=	-DCMAKE_CXX_COMPILER=${CXX}
LLVM_CMAKE_ARGS		+=	-DCMAKE_C_COMPILER=${CC}
LLVM_CMAKE_ARGS		+=	-DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL_PATH}

ifeq (${BUILD_TYPE}, RELEASE)
	LLVM_CMAKE_ARGS	+=	-DCMAKE_BUILD_TYPE=Release
endif
ifeq (${BUILD_TYPE}, DEBUG)
	LLVM_CMAKE_ARGS	+=	-DCMAKE_BUILD_TYPE=Debug
endif

LLVM_CMAKE_ARGS		+=	-DLLVM_ENABLE_RUNTIMES=${LLVM_RUNTIMES}
