.EXPORT_ALL_VARIABLES:

RAY_PATH		?=	ext/raylib/src
RAYLIBCPP_PATH	?=	ext/raylib-cpp/include
PLATFORM		?=	PLATFORM_DESKTOP

RAYLIB_LIBTYPE 				?=	SHARED
RAYLIB_INSTALL_PATH 		?=	${LIB_PATH}
RAYLIB_H_INSTALL_PATH 		?=	${INC_PATH}
RAYLIB_BUILD_MODE 			?=	${BUILD_TYPE}
RAYLIB_CONFIG_FLAGS  		?=	NONE
RAYLIB_MODULE_AUDIO  		?=	TRUE
RAYLIB_MODULE_MODELS 		?=	TRUE
USE_WAYLAND_DISPLAY   		?=	FALSE

RAYLIBCPP_H_INSTALL_PATH	?=	${INC_PATH}/raycpp

RAYLIB_HPP_FILES 			:=	$(patsubst ${RAYLIBCPP_PATH}/%.hpp,${RAYLIBCPP_H_INSTALL_PATH}/%.hpp,$(wildcard ${RAYLIBCPP_PATH}/*.hpp))

RAYLIB_CFLAGS				+= -Wno-old-style-cast
