include(AddIfFlagCompiles)

add_if_flag_compiles(-Og    				CMAKE_CXX_FLAGS_DEBUG)
add_if_flag_compiles(-ggdb  				CMAKE_CXX_FLAGS_DEBUG)
add_if_flag_compiles(-Ofast                 CMAKE_CXX_FLAGS_RELEASE)

if (CMAKE_BUILD_TYPE EQUAL "Debug")
	add_compile_definitions("RAYGAME_LOG_DEBUG")
else()
	add_compile_definitions("RAYGAME_LOG_INFO")
endif()

if (ENABLE_LTO)
	set_target_properties(${PROJECT_NAME} PROPERTIES INTERPROCEDURAL_OPTIMIZATION TRUE)
endif()

if (ENABLE_MSAN AND ENABLE_ASAN)
    MESSAGE(WARNING "Compiling with both AddressSanitizer and MemorySanitizer is not recommended")
endif()

if (ENABLE_ASAN)
    add_if_flag_compiles(-fno-omit-frame-pointer 								CMAKE_CXX_FLAGS CMAKE_LINKER_FLAGS)
    add_if_flag_compiles(-fsanitize=address 									CMAKE_CXX_FLAGS CMAKE_LINKER_FLAGS)
endif()

if (ENABLE_MSAN)
    add_if_flag_compiles(-fno-omit-frame-pointer 								CMAKE_CXX_FLAGS CMAKE_LINKER_FLAGS)
    add_if_flag_compiles(-fsanitize=memory 										CMAKE_CXX_FLAGS CMAKE_LINKER_FLAGS)
endif()

if (ENABLE_UBSAN)
    add_if_flag_compiles(-fno-omit-frame-pointer 								CMAKE_C_FLAGS CMAKE_LINKER_FLAGS)
    add_if_flag_compiles(-fsanitize=undefined 									CMAKE_C_FLAGS CMAKE_LINKER_FLAGS)
endif()

add_if_flag_compiles(-fdelete-null-pointer-checks                              	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-fsanitize=undefined                                      	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-fsized-deallocation                                      	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-fstack-protector                                         	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-fstrict-enums                                            	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)

add_if_flag_compiles(-Wall                                                     	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wextra                                                   	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wpedantic                                                	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wdeprecated                                              	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wabi                                                      CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wdirect-ivar-access                                      	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Weffc++                                                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wempty-init-stmt                                         	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wempty-translation-unit                                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wexplicit-ownership-type                                 	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wformat                                                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wformat-pedantic                                         	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wformat-type-confusion                                   	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wformat-zero-length                                      	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wfour-char-constants                                     	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wframe-address                                           	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wgcc-compat                                              	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wgnu                                                     	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wheader-hygiene                                          	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wimport-preprocessor-directive-pedantic                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wimplicit-function-declaration                           	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wincompatible-function-pointer-types-strict              	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wincomplete-module                                       	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Winconsistent-missing-destructor-override                	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Winfinite-recursion                                      	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wint-in-bool-context                                     	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wmicrosoft                                               	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wmisleading-indentation                                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wmissing-braces                                          	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wmove                                                    	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnewline-eof                                             	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnon-gcc                                                 	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnonportable-cfstrings                                   	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnonportable-include-path                                	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnonportable-system-include-path                         	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnonportable-vector-initialization                       	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnull-pointer-arithmetic                                 	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wnull-pointer-subtraction                                	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wold-style-cast                                          	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wpedantic-core-features                                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wpointer-arith                                           	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wrange-loop-construct                                    	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wredundant-move                                          	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wreserved-macro-identifier                               	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wshadow-all                                              	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wsign-compare                                            	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wsign-conversion                                         	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wtautological-compare                                    	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wthread-safety                                           	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wundef                                                   	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wundef-prefix                                            	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wunused                                                  	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wvariadic-macros                                         	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wvector-conversion                                       	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wvla                                                     	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wzero-as-null-pointer-constant                           	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
add_if_flag_compiles(-Wzero-length-array                                       	CMAKE_CXX_FLAGS CMAKE_LINTER_FLAGS)
