include_guard()
include(RayGameSetup)

function(raygame_add_args _target)
    if(MSVC)
        # Baseline reasonable warnings
        target_compile_options(${_target} PRIVATE /W4)
        target_compile_options(${_target} PRIVATE /w14242)
        target_compile_options(${_target} PRIVATE /w14254)
        target_compile_options(${_target} PRIVATE /w14263)
        target_compile_options(${_target} PRIVATE /w14265)
        target_compile_options(${_target} PRIVATE /w14287)
        target_compile_options(${_target} PRIVATE /we4289)
        target_compile_options(${_target} PRIVATE /w14296)
        target_compile_options(${_target} PRIVATE /w14311)
        target_compile_options(${_target} PRIVATE /w14545)
        target_compile_options(${_target} PRIVATE /w14546)
        target_compile_options(${_target} PRIVATE /w14547)
        target_compile_options(${_target} PRIVATE /w14549)
        target_compile_options(${_target} PRIVATE /w14555)
        target_compile_options(${_target} PRIVATE /w14619)
        target_compile_options(${_target} PRIVATE /w14640)
        target_compile_options(${_target} PRIVATE /w14826)
        target_compile_options(${_target} PRIVATE /w14905)
        target_compile_options(${_target} PRIVATE /w14906)
        target_compile_options(${_target} PRIVATE /w14928)
        target_compile_options(${_target} PRIVATE /permissive-)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
        target_compile_options(${_target} PRIVATE -Wall)
        target_compile_options(${_target} PRIVATE -Wextra)
        target_compile_options(${_target} PRIVATE -Weverything)
        target_compile_options(${_target} PRIVATE -pedantic)
        target_compile_options(${_target} PRIVATE -Wthread-safety)
        target_compile_options(${_target} PRIVATE -Wself-assign)
        target_compile_options(${_target} PRIVATE -Wno-padded)
        target_compile_options(${_target} PRIVATE -Wno-c99-extensions)
        target_compile_options(${_target} PRIVATE -Wno-c99-compat)
        target_compile_options(${_target} PRIVATE -Wno-c++-compat)
        target_compile_options(${_target} PRIVATE -Wno-c++98-compat)
        target_compile_options(${_target} PRIVATE -Wno-c++98-compat-pedantic)
        target_compile_options(${_target} PRIVATE -Wno-c++20-compat)
        target_compile_options(${_target} PRIVATE -Wno-pre-c++20-compat-pedantic)
        target_compile_options(${_target} PRIVATE -Wno-pre-c++17-compat-pedantic)
        target_compile_options(${_target} PRIVATE -Wno-switch-default)
        target_compile_options(${_target} PRIVATE -Wno-c++20-extensions)
        target_compile_options(${_target} PRIVATE -Wno-unused-macros)
        target_compile_options(${_target} PRIVATE -Wno-unsafe-buffer-usage)
        target_compile_options(${_target} PRIVATE -Wno-c23-extensions)
        target_compile_options(${_target} PRIVATE -Wno-unused-command-line-argument)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${_target} PRIVATE -Wall)
        target_compile_options(${_target} PRIVATE -Wextra)
        target_compile_options(${_target} PRIVATE -Wshadow)
        target_compile_options(${_target} PRIVATE -Wnon-virtual-dtor)
        target_compile_options(${_target} PRIVATE -Wold-style-cast)
        target_compile_options(${_target} PRIVATE -Wcast-align)
        target_compile_options(${_target} PRIVATE -Wunused)
        target_compile_options(${_target} PRIVATE -Woverloaded-virtual)
        target_compile_options(${_target} PRIVATE -Wpedantic)
        target_compile_options(${_target} PRIVATE -Wconversion)
        target_compile_options(${_target} PRIVATE -Wsign-conversion)
        target_compile_options(${_target} PRIVATE -Wnull-dereference)
        target_compile_options(${_target} PRIVATE -Wdouble-promotion)
        target_compile_options(${_target} PRIVATE -Wformat=2)
        target_compile_options(${_target} PRIVATE -Wimplicit-fallthrough)
        target_compile_options(${_target} PRIVATE -Wmisleading-indentation)
        target_compile_options(${_target} PRIVATE -Wduplicated-cond)
        target_compile_options(${_target} PRIVATE -Wduplicated-branches)
        target_compile_options(${_target} PRIVATE -Wlogical-op)
        target_compile_options(${_target} PRIVATE -Wuseless-cast)
        target_compile_options(${_target} PRIVATE -Wsuggest-override)
        target_compile_options(${_target} PRIVATE -Wno-return-type)
        target_compile_options(${_target} PRIVATE -Wno-duplicate-branches)
    else()
        message(FATAL_ERROR "No compiler warnings set for CXX compiler: '${CMAKE_CXX_COMPILER_ID}'")
    endif()
endfunction()
