add_subdirectory(${RG_PATH_ETC}/doctest ${CMAKE_CURRENT_BINARY_DIR}/doctest)
function(rg_make_test TARGET)
    set(options)
    set(oneValueArgs)
    set(multiValueArgs LIBS SOURCES)
    cmake_parse_arguments(RG_ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    target_compile_options(${TARGET} PRIVATE -Wno-unsafe-buffer-usage)
    target_link_libraries(${TARGET} PRIVATE ${LIBS} doctest::doctest)
    rg_add_args(${TARGET})
endfunction()
