config_setting(
    name = "trace",
    flag_values = { "//rules/log:level": "trace" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "debug",
    flag_values = { "//rules/log:level": "debug" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "info",
    flag_values = { "//rules/log:level": "info" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "warning",
    flag_values = { "//rules/log:level": "warning" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "error",
    flag_values = { "//rules/log:level": "error" },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "fatal",
    flag_values = { "//rules/log:level": "fatal" },
    visibility = ["//visibility:public"],
)
