load("//rules:rg_cc.bzl", "rg_cc_singletest")

rg_cc_singletest(
    name = "arithmetic",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "math",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "mathrule",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "numeric_cast",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "random",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "rect",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "ring_average",
    deps = ["//raygame/core/math"],
)

rg_cc_singletest(
    name = "vector",
    deps = ["//raygame/core/math"],
)
