name: CMake on multiple platforms
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        cpp_compiler: [clang]
        use_wayland: [ON]
        include:
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            use_wayland: ON
    steps:
    - uses: actions/checkout@v4
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "build-source-dir=${{ github.workspace }}/src" >> "$GITHUB_OUTPUT"
    - name: Configure CMake
      run: >
        cmake -G Ninja
        -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ steps.strings.outputs.build-source-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DRAYGAME_GUI_USE_WAYLAND=${{ matrix.use_wayland }}
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
